version: "3.4"

services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongovol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  netmaker:
    privileged: true
    container_name: netmaker
    depends_on:
      - mongodb
    image: gravitl/netmaker:v0.3
    ports:
      - "8081:8081"
      - "50051:50051"
    volumes:
      - ./:/local
      - /etc/netclient:/etc/netclient
      - dnsconfig:/root/config/dnsconfig
      - /usr/bin/wg:/usr/bin/wg:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /run/systemd/system:/run/systemd/system
      - /etc/systemd/system:/etc/systemd/system
      - /sys/fs/cgroup:/sys/fs/cgroup
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    network_mode: host
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.3
    links:
      - "netmaker:api"
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://3.236.149.180:8081"
  coredns:
    depends_on:
      - netmaker 
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - dnsconfig:/root/dnsconfig
volumes:
  mongovol: {}
  dnsconfig: {}
