name: Build for all ARCH/OS

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.18
      - name: Build
        run: |
         sudo make all
