name: Build for all ARCH/OS

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
         make install-go
         sudo ./install-go
         sudo make all
