name: Integration Test

on:
  push:

jobs:
  tests:
    env:
      DATABASE: sqlite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run tests
        run: |
            go test -p 1 ./... -v
        env:
          DATABASE: sqlite
          CLIENT_MODE: "off"
