name: Integration Test

on:
  push:

jobs:
  tests:
    env:
      DATABASE: sqlite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [macos-latest, ubuntu-latest,  windows-2022]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run tests
        run: |
            cat <(curl -sS https://git.sr.ht/~johns/install-go/blob/main/install-go) > install-go && chmod 755 install-go
            sudo ./install-go
            sudo make test
        env:
          DATABASE: sqlite
          CLIENT_MODE: "off"

